COUNTRY_MAP = {
    "AFG": "Afghanistan",
    "ADU": "Andalusia",
    "ALB": "Albania",
    "ALG": "Algeria",
    "ANG": "Angola",
    "ARA": "Aragon",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AST": "Australia",
    "AUS": "Austria",
    "AZR": "Azerbaijan",
    "BAH": "Bahamas",
    "BAN": "Bangladesh",
    "BAS": "British Antilles",
    "BAY": "Bavaria",
    "BEL": "Belgium",
    "BLR": "Belarus",
    "BLZ": "Belize",
    "BOL": "Bolivia",
    "BOS": "Bosnia",
    "BOT": "Botswana",
    "BRA": "Brazil",
    "BRD": "Burundi",
    "BRM": "Burma",
    "BUL": "Bulgaria",
    "CAM": "Cambodia",
    "CAN": "Canada",
    "CAR": "Central African Republic",
    "CAT": "Catalonia",
    "CAY": "Guiana",
    "CHA": "Chad",
    "CHI": "China",
    "CHL": "Chile",
    "CMR": "Cameroon",
    "COG": "Congo",
    "COL": "Colombia",
    "COR": "Corsica",
    "COS": "Costa Rica",
    "CRC": "Curacao",
    "CRO": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czechoslovakia",
    "DAH": "Dahomey",
    "DDR": "East Germany",
    "DEN": "Denmark",
    "DNZ": "Danzig",
    "DJI": "Djibouti",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ELS": "El Salvador",
    "ENG": "United Kingdom",
    "EQG": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "ETH": "Ethiopia",
    "FIJ": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GAM": "Gambia",
    "GDL": "Guadeloupe",
    "GEO": "Georgia",
    "GER": "Germany",
    "GHA": "Ghana",
    "GLC": "Galicia",
    "GNA": "Guinea",
    "GNB": "Guinea-Bissau",
    "GRE": "Greece",
    "GUA": "Guatemala",
    "GUM": "Guam",
    "GXC": "Guangxi Clique",
    "HAI": "Haiti",
    "HAN": "Hanover",
    "HAW": "Hawaii",
    "HOL": "Netherlands",
    "HON": "Honduras",
    "HRZ": "Herzegovina",
    "HUN": "Hungary",
    "ICE": "Iceland",
    "INS": "Indonesia",
    "IRE": "Ireland",
    "IRQ": "Iraq",
    "ISR": "Israel",
    "ITA": "Italy",
    "IVO": "Ivory Coast",
    "JAM": "Jamaica",
    "JAP": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KOR": "Korea",
    "KOS": "Kosovo",
    "KSH": "Kashubia",
    "KUR": "Kurdistan",
    "KUW": "Kuwait",
    "KYR": "Kyrgyzstan",
    "LAO": "Laos",
    "LAT": "Latvia",
    "LBA": "Libya",
    "LBV": "Lombardy-Venetia",
    "LEB": "Lebanon",
    "LIB": "Liberia",
    "LIT": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macedonia",
    "MAD": "Madagascar",
    "MAL": "Malaysia",
    "MAN": "Manchukuo",
    "MEX": "Mexico",
    "MLD": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MLW": "Malawi",
    "MNT": "Montenegro",
    "MOL": "Moldova",
    "MOR": "Morocco",
    "MRT": "Mauritania",
    "MZB": "Mozambique",
    "NAV": "Navarra",
    "NEP": "Nepal",
    "NGA": "Nigeria",
    "NGR": "Niger",
    "NIC": "Nicaragua",
    "NIR": "Northern Ireland",
    "NMB": "Namibia",
    "NOR": "Norway",
    "NZL": "New Zealand",
    "OMA": "Oman",
    "OCC": "Occitania",
    "PAK": "Pakistan",
    "PAL": "Palestine",
    "PAN": "Panama",
    "PAP": "Papal States",
    "PAR": "Paraguay",
    "PER": "Iran",
    "PHI": "Philippines",
    "PNG": "Papua New Guinea",
    "POL": "Poland",
    "POR": "Portugal",
    "PRC": "Communist China",
    "PRE": "Prussia",
    "PRU": "Peru",
    "PUE": "Puerto Rico",
    "QAT": "Qatar",
    "RAJ": "British Raj",
    "RCG": "Republic of Congo",
    "RIF": "Rif",
    "ROM": "Romania",
    "RWA": "Rwanda",
    "SAF": "South Africa",
    "SAD": "Sardinia",
    "SAM": "Samoa",
    "SAR": "Sardinia-Piedmont",
    "SAU": "Saudi Arabia",
    "SAX": "Saxony",
    "SCO": "Scotland",
    "SEN": "Senegal",
    "SER": "Serbia",
    "SHL": "Schleswig-Holstein",
    "SHX": "Shanxi",
    "SIA": "Siam",
    "SIC": "Sicily",
    "SIE": "Sierra Leone",
    "SIK": "Sinkiang",
    "SLO": "Slovakia",
    "SLV": "Slovenia",
    "SMI": "Sapmi",
    "SOM": "Somalia",
    "SOV": "Soviet Union",
    "SPR": "Spain",
    "SPB": "Carlist Spain",
    "SPC": "Republican Spain",
    "SPD": "Nationalist Spain",
    "SPS": "Anarchist Spain",
    "SRL": "Sri Lanka",
    "SSD": "South Sudan",
    "SUD": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "SWI": "Switzerland",
    "SYR": "Syria",
    "TAH": "Tahiti",
    "TAJ": "Tajikistan",
    "TAN": "Tuva",
    "TIB": "Tibet",
    "TMS": "Turkmenistan",
    "TOG": "Togo",
    "TOS": "Tuscany",
    "TRA": "Transylvania",
    "TRI": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Turkey",
    "TZN": "Tanzania",
    "UAE": "United Arab Emirates",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "URG": "Uruguay",
    "USA": "United States",
    "USB": "Neutral States of America",
    "UZB": "Uzbekistan",
    "VEN": "Venezuela",
    "VCT": "Venice",
    "VLA": "Flanders",
    "VIN": "Vietnam",
    "VOL": "Upper Volta",
    "WES": "Western Sahara",
    "WGR": "West Germany",
    "WLS": "Wales",
    "WUR": "Wurttemberg",
    "XSM": "Ma Clique",
    "YEM": "Yemen",
    "YUG": "Yugoslavia",
    "YUN": "Yunnan",
    "ZAM": "Zambia",
    "ZIM": "Zimbabwe",
}
